# Cleaning and Preparation of Prime2 Road Network Data

This section outlines the processing of the Prime2 national road network dataset to create a walkable network for accessibility analysis. The workflow involves filtering and cleaning the Prime2 road features, retaining only relevant attributes, and classifying road segments based on their functional type and pedestrian accessibility. Walking speeds are assigned to each road segment, and travel times are calculated to facilitate pedestrian network modeling. The resulting cleaned and enriched dataset is used to construct the walk and public transport network for subsequent accessibility analysis.

In [34]:
#imports required libraries
import geopandas as gpd

In [35]:
#Reads Way_GDF2_DCC shapefile
Way_gdf2 = gpd.read_file(r"D:\GIS-TU Dublin\Year_2\THESIS\DCC_Analysis\Data_used\Prime2_Data\Way_GDF2_DCC.shp")

In [36]:
#Shows all the information related to way_gdf2 prime2 data
Way_gdf2.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 15344 entries, 0 to 15343
Data columns (total 86 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   END_PNT_GU  15344 non-null  object
 1   GUID        15344 non-null  object
 2   START_PNT_  15344 non-null  object
 3   URI         0 non-null      object
 4   ACCESS_CAP  15344 non-null  object
 5   ACCESS_CHA  15344 non-null  object
 6   ACCESS_VAL  15344 non-null  object
 7   DIRECTION_  15344 non-null  object
 8   DIRECTION1  15344 non-null  object
 9   DIRECTIO_1  15344 non-null  object
 10  FORM_CAPTU  15344 non-null  object
 11  FORM_CHANG  15344 non-null  object
 12  FORM_VALID  15344 non-null  object
 13  FUNC_CAPTU  15344 non-null  object
 14  FUNC_CHANG  15344 non-null  object
 15  FUNC_VALID  15344 non-null  object
 16  LINE_GEOM_  15344 non-null  object
 17  LINE_GEOM1  15344 non-null  object
 18  LINE_GEO_1  15344 non-null  object
 19  MAX_AXLES_  0 non-null      object
 20  MAX_AXLES1  0 non-null      object
 21  MAX_AXLE_1  0 non-null      object
 22  MAX_HT_CAP  47 non-null     object
 23  MAX_HT_CHA  47 non-null     object
 24  MAX_HT_VAL  47 non-null     object
 25  MAX_WD_CAP  0 non-null      object
 26  MAX_WD_CHA  0 non-null      object
 27  MAX_WD_VAL  0 non-null      object
 28  MAX_WT_CAP  0 non-null      object
 29  MAX_WT_CHA  0 non-null      object
 30  MAX_WT_VAL  0 non-null      object
 31  STATUS_CAP  15344 non-null  object
 32  STATUS_CHA  15344 non-null  object
 33  STATUS_VAL  15344 non-null  object
 34  Z_ORDER_CA  15344 non-null  object
 35  Z_ORDER_CH  15344 non-null  object
 36  Z_ORDER_VA  15344 non-null  object
 37  Z_ORDER__1  15344 non-null  int64
 38  Z_ORDER__2  15344 non-null  int64
 39  Z_ORDER__3  15344 non-null  int64
 40  Z_ORDER__4  15344 non-null  int64
 41  STATUS_ID   15344 non-null  int64
 42  STATUS_C_1  15344 non-null  int64
 43  STATUS_V_1  15344 non-null  int64
 44  STATUS_C_2  15344 non-null  int64
 45  MAX_WT_V_1  15344 non-null  int64
 46  MAX_WT_V_2  15344 non-null  int64
 47  MAX_WT_C_1  15344 non-null  int64
 48  MAX_WT_C_2  15344 non-null  int64
 49  MAX_WD_V_1  15344 non-null  int64
 50  MAX_WD_V_2  15344 non-null  int64
 51  MAX_WD_C_1  15344 non-null  int64
 52  MAX_WD_C_2  15344 non-null  int64
 53  MAX_HT_V_1  15344 non-null  int64
 54  MAX_HT_V_2  15344 non-null  int64
 55  MAX_HT_C_1  15344 non-null  int64
 56  MAX_HT_C_2  15344 non-null  int64
 57  MAX_AXLE_2  15344 non-null  int64
 58  MAX_AXLE_3  15344 non-null  int64
 59  MAX_AXLE_4  15344 non-null  int64
 60  MAX_AXLE_5  15344 non-null  int64
 61  LINE_GEO_2  15344 non-null  int64
 62  LINE_GEO_3  15344 non-null  int64
 63  LINE_GEO_4  15344 non-null  int64
 64  LINE_GEO_5  15344 non-null  int64
 65  LINE_GEO_6  15344 non-null  int64
 66  LINE_GEO_7  15344 non-null  int64
 67  FUNC_VAL_1  15344 non-null  int64
 68  FUNC_ID     15344 non-null  int64
 69  FUNC_CHA_1  15344 non-null  int64
 70  FUNC_CAP_1  15344 non-null  int64
 71  FORM_VAL_1  15344 non-null  int64
 72  FORM_ID     15344 non-null  int64
 73  FORM_CHA_1  15344 non-null  int64
 74  ACCESS_C_1  15344 non-null  int64
 75  CAPTURE_SP  15344 non-null  int64
 76  DIRECTIO_2  15344 non-null  int64
 77  DIRECTIO_3  15344 non-null  int64
 78  FORM_CAP_1  15344 non-null  int64
 79  DIRECTIO_4  15344 non-null  int64
 80  DIRECTIO_5  15344 non-null  int64
 81  ACCESS_V_1  15344 non-null  int64
 82  ACCESS_ID   15344 non-null  int64
 83  ACCESS_C_2  15344 non-null  int64
 84  Shape_Leng  15344 non-null  float64
 85  geometry    15344 non-null  geometry
dtypes: float64(1), geometry(1), int64(47), object(37)
memory usage: 10.1+ MB

In [71]:
#shows first 2 rows of dataframe
Way_gdf2.head(2)

                             END_PNT_GU  ...                                           geometry
0  403f686e-05d5-4302-8632-76ab7ac899fa  ...  LINESTRING Z (721845.332 738194.297 0.000, 721...
1  3b008afe-bcb4-4035-b158-b956934508fd  ...  LINESTRING Z (722756.985 739914.019 0.000, 722...

[2 rows x 86 columns]

In [72]:
#Only keeps the required column
keep = [
    # ids & geometry
    "GUID", "START_PNT_", "END_PNT_GU", "geometry",
    # length
    "Shape_Leng",
    # form/functional/access/direction
    "FORM_VAL_1", "FORM_ID",
    "FUNC_VAL_1", "FUNC_ID",
    "ACCESS_VAL", "ACCESS_ID",
    "DIRECTION_", "DIRECTIO_2",
    # z-order (keep just one)
    "Z_ORDER__4"
]
keep = [c for c in keep if c in Way_gdf2.columns]

Way_gdf2_clean = Way_gdf2[keep].copy()

Way_gdf2_clean.head()

                                   GUID  ... Z_ORDER__4
0  0f18bd8f-5441-48ff-8343-95f250df061f  ...          1
1  fa145cf4-b979-4bfa-a07b-f5c250977573  ...          1
2  aa260a66-0d2b-466a-8cf7-fe41cb5191b3  ...          1
3  397739b3-4c5f-40e2-a461-7f9c4eab6724  ...          1
4  9ca50adc-6481-4682-a7f2-7426d1db8b97  ...          1

[5 rows x 14 columns]

In [73]:
#Shows the unique values of column 'FORM_VAL_1'
Way_gdf2_clean['FORM_VAL_1'].value_counts()

1    15344
Name: FORM_VAL_1, dtype: int64

In [74]:
#Shows the unique values of column 'FORM_VAL_1'
Way_gdf2_clean['FORM_VAL_1'].value_counts()

1    15344
Name: FORM_VAL_1, dtype: int64

In [75]:
#Shows the unique values of column 'FUNC_ID'
Way_gdf2_clean['FUNC_ID'].value_counts()

191    9569
475    2176
409    2103
667    1233
177     130
266      84
660      26
659      20
662       2
661       1
Name: FUNC_ID, dtype: int64

In [76]:
#Shows the unique values of column 'ACCESS_ID'
Way_gdf2_clean['ACCESS_ID'].value_counts()

1    15259
5       69
4       15
7        1
Name: ACCESS_ID, dtype: int64

In [77]:
#Shows the unique values of column 'FORM_ID'
Way_gdf2_clean['FORM_ID'].value_counts()

362    15060
122      196
246       37
369       23
281       21
215        5
411        1
655        1
Name: FORM_ID, dtype: int64

In [78]:
#Shows the unique values of column 'Z_ORDER__4'
Way_gdf2_clean['Z_ORDER__4'].value_counts()

1    15344
Name: Z_ORDER__4, dtype: int64

In [90]:
 #--- Define lookup dicts ---
road_class_map = {
    667: "First Class (Motorway)",
    191: "Second Class",
    409: "Third Class (Access Only)",
    475: "Fourth Class",
    177: "Fifth Class",
    266: "Sixth Class",
    659: "Pedestrian Route",
    660: "Cycleway",
    661: "Slip Road",
    662: "Service Link"
}

speed_map = {
    667: 120,   # First Class
    191: 100,   # Second Class
    409: 80,    # Third Class
    475: 80,    # Fourth Class
    177: 50,    # Fifth Class (urban)
    266: 50,    # Sixth Class
    659: 3.6,   # Pedestrian Route (elderly, 1.0 m/s)
    660: 15,    # Cycleway
    661: 60,    # Slip Road
    662: 30     # Service Link
}

form_lookup = {
    362: "Single Carriageway",
    122: "Dual Carriageway",
    246: "Roundabout",
    369: "Slip Road",
    281: "Track / Local Lane",
    215: "Footpath",
    411: "Cycleway",
    655: "Service Road"
}

access_map = {
    1: "All Traffic",
    5: "Pedestrian Only",
    4: "Pedestrian & Cycle",
    7: "No Pedestrian Access"
}


# --- Create new fields ---
Way_gdf2_clean["ROAD_CLASS"] = Way_gdf2_clean["FUNC_ID"].map(road_class_map).fillna("Unknown")
Way_gdf2_clean["FormClass"] = Way_gdf2_clean["FORM_ID"].map(form_lookup).fillna("Unknown")
Way_gdf2_clean["AccessClass"] = Way_gdf2_clean["ACCESS_ID"].map(access_map).fillna("Unknown")
Way_gdf2_clean["Speed_kmh"]  = Way_gdf2_clean["FUNC_ID"].map(speed_map).fillna(50)  # fallback = 50 km/h
Way_gdf2_clean["Time"] = ((Way_gdf2_clean["Shape_Leng"] / 1000) / Way_gdf2_clean["Speed_kmh"] * 60).round(2)

In [91]:
#Displays first few rows
Way_gdf2_clean.head()

                                   GUID  ...  Time
0  0f18bd8f-5441-48ff-8343-95f250df061f  ...  0.19
1  fa145cf4-b979-4bfa-a07b-f5c250977573  ...  0.02
2  aa260a66-0d2b-466a-8cf7-fe41cb5191b3  ...  0.04
3  397739b3-4c5f-40e2-a461-7f9c4eab6724  ...  0.05
4  9ca50adc-6481-4682-a7f2-7426d1db8b97  ...  0.07

[5 rows x 19 columns]

In [92]:
#Checks CRS of dataframe
Way_gdf2_clean.crs

<Projected CRS: EPSG:2157>
Name: IRENET95 / Irish Transverse Mercator
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Ireland - onshore. United Kingdom (UK) - Northern Ireland (Ulster) - onshore.
- bounds: (-10.56, 51.39, -5.34, 55.43)
Coordinate Operation:
- name: Irish Transverse Mercator
- method: Transverse Mercator
Datum: IRENET95
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [104]:
#Displays first few rows
Way_gdf2_clean.head(2)

                                   GUID  ...  Time
0  0f18bd8f-5441-48ff-8343-95f250df061f  ...  0.19
1  fa145cf4-b979-4bfa-a07b-f5c250977573  ...  0.02

[2 rows x 19 columns]

In [106]:
# Save walk_gdf as shapefile
Way_gdf2_clean.to_file(r"D:\GIS-TU Dublin\Year_2\THESIS\DCC_Analysis\Data_used\Prime2_Data\transit_network.shp", driver="ESRI Shapefile")

In [94]:
# Display a summary of the GeoDataFrame, including column names, data types, and non-null counts
Way_gdf2_clean.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 15344 entries, 0 to 15343
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GUID         15344 non-null  object
 1   START_PNT_   15344 non-null  object
 2   END_PNT_GU   15344 non-null  object
 3   geometry     15344 non-null  geometry
 4   Shape_Leng   15344 non-null  float64
 5   FORM_VAL_1   15344 non-null  int64
 6   FORM_ID      15344 non-null  int64
 7   FUNC_VAL_1   15344 non-null  int64
 8   FUNC_ID      15344 non-null  int64
 9   ACCESS_VAL   15344 non-null  object
 10  ACCESS_ID    15344 non-null  int64
 11  DIRECTION_   15344 non-null  object
 12  DIRECTIO_2   15344 non-null  int64
 13  Z_ORDER__4   15344 non-null  int64
 14  ROAD_CLASS   15344 non-null  object
 15  FormClass    15344 non-null  object
 16  AccessClass  15344 non-null  object
 17  Speed_kmh    15344 non-null  float64
 18  Time         15344 non-null  float64
dtypes: float64(3), geometry(1), int64(7), object(8)
memory usage: 2.2+ MB

In [98]:
# Step 1: Drop motorways and major national roads for creating walk network
walk_gdf = Way_gdf2_clean[~Way_gdf2_clean["FUNC_ID"].isin([667])].copy()

print("Before:", len(Way_gdf2_clean))
print("After removing motorways/nationals:", len(walk_gdf))

Before: 15344
After removing motorways/nationals: 14111

In [99]:
# Step 2: Keep only pedestrian-allowed links
walk_gdf = walk_gdf[walk_gdf["ACCESS_ID"].isin([1, 4, 5])].copy()

print("After filtering pedestrian access:", len(walk_gdf))
print(walk_gdf["ACCESS_ID"].value_counts())

After filtering pedestrian access: 14110
1    14026
5       69
4       15
Name: ACCESS_ID, dtype: int64

In [102]:
# Step 3: Assign elderly walking speed and recompute time (minutes)

# 1 m/s = 3.6 km/h
WALK_KMH = 3.6
walk_gdf["Speed_kmh"] = WALK_KMH
# Time (minutes) = (distance km / speed km/h) * 60
walk_gdf["Time"] = ((walk_gdf["Shape_Leng"] / 1000) / walk_gdf["Speed_kmh"] * 60).round(2)
walk_gdf.head(2)

                                   GUID  ...  Time
0  0f18bd8f-5441-48ff-8343-95f250df061f  ...  4.16
1  fa145cf4-b979-4bfa-a07b-f5c250977573  ...  0.60

[2 rows x 19 columns]

In [103]:
# Save walk_gdf as shapefile
walk_gdf.to_file("D:\GIS-TU Dublin\Year_2\THESIS\DCC_Analysis\Data_used\Prime2_Data\walk_network.shp", driver="ESRI Shapefile")

[103]:2: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.